# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Jialing Huang
title: Junior Web Developer
email: jialing.huang@hotmail.com
#website: www.github.com/sproogen/resume-theme

# Social links
#twitter_username: facespics
github_username:  Jialing-Huang
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: Professional Skill
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jialing and I'm looking for a job position as junior Web Developer. 

  I am most skilled in:
  
  Web Development Framework: <mark>Angular</mark>   &   <mark>ASP.NET CORE</mark>
  
  Programming Language: <mark>JavaScript</mark>   &    <mark>TypeScript</mark>   &   <mark>Java</mark>  &  <mark>PHP</mark>
  
  Web Coding Library: <mark>jQuery</mark>   &    <mark>node.js</mark>   &   <mark>d3.js</mark> 
  
  Database Skill: <mark>SQL</mark> & <mark>MongoDB</mark>
  
  Web Development Basic Skill:<mark>Html</mark>   &    <mark>CSS</mark>   &   <mark>DOM</mark> 
  
  Web Development Kit: <mark>Postman</mark>   &    <mark>Git</mark> 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-cayman
